#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

wclean src/libcompressibleInterIsoLptFoam

wclean applications/compressibleInterIsoLptFoam

#------------------------------------------------------------------------------
